dist: trusty

matrix:
  include:
    - language: python
      python: 2.7
      env: CHECK=pylint
      # command to install dependencies
      install:
        - "pip install --upgrade setuptools"
        - "pip install --upgrade pip"
        - "pip install -r requirements.txt"
      script:
        - export PYTHONPATH=${PWD%/*}
        - ls $PYTHONPATH
        - travis_wait 30 .travis.d/runPylint.sh

    - language: python
      python: 2.7
      env: CHECK=format
      # command to install dependencies
      install:
        - "pip install --upgrade setuptools"
        - "pip install --upgrade pip"
        - "pip install -r requirements.txt"
      script:
        - export PYTHONPATH=${PWD%/*}
        - ls $PYTHONPATH
          if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]];
          then git remote add GH https://github.com/DIRACGrid/WebAppDIRAC.git; git fetch --no-tags GH ${TRAVIS_BRANCH}; git branch -vv; git diff -U0 GH/${TRAVIS_BRANCH} | pycodestyle --diff;
          fi


    - language: node_js
      node_js: 7
      env: CHECK=eslint
      install:
        - npm install eslint
      script:
        - eslint WebApp
